#!/usr/bin/env python3
"""Refresh the checked-in GitHub star snapshot used by the static site."""

from datetime import datetime, timezone
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import time
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"
SNAPSHOT = ROOT / "github-stars-data.js"
SNAPSHOT_RE = re.compile(r'"([^"]+/[^"]+)":\s*(\d+),')


class GitHubRepoParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.repos = set()

    def handle_starttag(self, tag, attrs):
        if tag != "a":
            return
        href = dict(attrs).get("href", "")
        url = urlsplit(href)
        parts = url.path.strip("/").split("/")
        if url.netloc.lower() == "github.com" and len(parts) == 2:
            self.repos.add("/".join(parts))


def repository_names():
    parser = GitHubRepoParser()
    parser.feed(INDEX.read_text())
    return sorted(parser.repos, key=str.casefold)


def current_snapshot():
    if not SNAPSHOT.exists():
        return {}
    return {repo: int(count) for repo, count in SNAPSHOT_RE.findall(SNAPSHOT.read_text())}


def fetch_star_count(repo, token):
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "KDharmarajanDev.github.io-star-refresh",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = Request(f"https://api.github.com/repos/{repo}", headers=headers)
    for attempt in range(3):
        try:
            with urlopen(request, timeout=20) as response:
                value = json.load(response).get("stargazers_count")
                if not isinstance(value, int):
                    raise ValueError("response has no integer stargazers_count")
                return value
        except HTTPError as error:
            if error.code not in {403, 429, 500, 502, 503, 504} or attempt == 2:
                raise
        except (URLError, TimeoutError, ValueError):
            if attempt == 2:
                raise
        time.sleep(2**attempt)


def write_snapshot(counts):
    updated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    lines = [
        "// Generated by scripts/update-github-stars.py. Do not edit manually.",
        "const githubStarsSnapshot = Object.freeze({",
        f'  updatedAt: "{updated_at}",',
        "  repos: Object.freeze({",
    ]
    lines.extend(f'    "{repo}": {counts[repo]},' for repo in sorted(counts, key=str.casefold))
    lines.extend(["  }),", "});", ""])
    SNAPSHOT.write_text("\n".join(lines))


def main():
    repos = repository_names()
    previous = current_snapshot()
    counts = {}
    failures = []
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")

    for repo in repos:
        try:
            counts[repo] = fetch_star_count(repo, token)
            print(f"{repo}: {counts[repo]}")
        except (HTTPError, URLError, TimeoutError, ValueError) as error:
            failures.append(f"{repo}: {error}")

    if failures:
        suffix = "\nThe previous snapshot was left unchanged." if previous else ""
        raise SystemExit("Could not create a complete snapshot:\n- " + "\n- ".join(failures) + suffix)

    write_snapshot(counts)
    print(f"Updated {SNAPSHOT.relative_to(ROOT)} with {len(counts)} repositories.")


if __name__ == "__main__":
    main()
